individuals: individuals.tsv
units: units.tsv

restriction-enzyme:
  p5: NsiI
  p7: Csp6I

params:
  stacks:
    - max_individual_mm: 4
      max_locus_mm: 4
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 4
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 7
      min_reads: 3
  # command line parameters for gstacks, except -I, -O, -B
  gstacks: ""
  process_radtags: "--index_null"
  cutadapt: "-q 20"
