individuals: individuals.tsv
units: units.tsv

params:
  stacks:
    - individual: 4
      locus: 4
      min_reads: 3
    - individual: 5
      locus: 5
      min_reads: 3
    - individual: 6
      locus: 6
      min_reads: 3
    - individual: 4
      locus: 5
      min_reads: 3
    - individual: 5
      locus: 6
      min_reads: 3
    - individual: 6
      locus: 7
      min_reads: 3
  # command line parameters for gstacks, except -I, -O, -B
  gstacks: ""
