individuals: individuals.tsv
units: units.tsv

restriction-enzyme:
  p5: nsiI
  p7: csp6I

dbr:
  len: 13
  # maximum hamming distance of DBR to be considered a duplicate
  max_dist: 2
  # maximum hamming distance of read sequence to be considered a duplicate
  max_seq_dist: 2

# Illumina sequencing adapter that shall be trimmed away.
# Leave empty if no trimming shall be performed.
adapter: ""

reads:
  length: 100
  join_seq: NNNNN

params:
  stacks:
    - max_individual_mm: 4
      max_locus_mm: 4
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 4
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 7
      min_reads: 3
  # command line parameters for gstacks, except -I, -O, -B
  gstacks: ""
  process_radtags: "--inline_null -q -r --barcode_dist_1 3 -D"
  kraken:
    # refer to kraken DB, see https://ccb.jhu.edu/software/kraken/
    db: kraken/kraken.db
  call_consensus_reads:
    umi_len: 8
    max_umi_dist: 1
    max_seq_dist: 2
