# define individuals and sequencing units
individuals: individuals.tsv
units: units.tsv

# define the used restriction enzymes
restriction-enzyme:
  p5:
    name: nsiI
    residue-len: 5
  p7:
    name: csp6I
    residue-len: 3

# DBR/UMI handling
umi:
  # length of DBR/UMI
  len: 13
  # maximum hamming distance of UMI to be considered a duplicate
  max_dist: 1
  # maximum hamming distance of read sequence to be considered a duplicate
  max_seq_dist: 2

reads:
  # Expected read length.
  length: 100
  # Spacer sequence to join paired end reads.
  join_seq: NNNNN
  # Read handling mode. This parameter is used to specify
  # input files for ustacks, via the force_same_length rule and the
  # trim_input function.
  #
  # Currently three modes are supported: ["p5_only", "merged", "concatenated"]
  # 
  # "p5_only" uses only the p5 reads, completely ignoring p7 reads.
  # "merged" merges p5 and p7 read pairs into one long pseudo-single-end read
  # "concatenated" appends the p7 reads to the p5 read file.
  mode: "merged"

# parameters for tools used in the pipeline
params:
  stacks:
    - max_individual_mm: 4
      max_locus_mm: 4
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 4
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 6
      min_reads: 3
    - max_individual_mm: 6
      max_locus_mm: 7
      min_reads: 3
  # command line parameters for gstacks, except -I, -O, -B
  gstacks: ""
  # command line parameters for process_radtags
  process_radtags: "--inline_null -q -r --barcode_dist_1 3 -D"
  populations:
    # Desired output formats for the stacks populations script.
    # Possible values are vcf, genepop, fasta, phylip
    output_types:
      - vcf
      - genepop
      - fasta
      - phylip
  kraken:
    # Refer to kraken DB folder, see https://ccb.jhu.edu/software/kraken.
    # Kraken is used to classify reads for possible contaminations.
    # Comment out or leave empty in order to disable kraken.
    db: data/kraken
